server.port : 8090

spring:
    thymeleaf:
        cache: false
    jackson:
        serialization:
            FAIL_ON_EMPTY_BEANS: false
    devtools:
        restart:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate.format_sql: true
        show-sql: true
        globally_quoted_identifiers: true
    datasource:
        dbcp2:
            driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/trendchecker
        username: root
        password: root
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}
                        scope:
                            - profile_nickname
                            - profile_image
                            - profile_email
                    kakao:
                        client-id: c7e711c3d2a9753d934857afd26e3b82
                        client-secret: cj9vJILREW2tb4VUNwBlhfmpJNXEVoUH
                        redirect-uri: http://localhost:8090/login/oauth2/code/kakao
                        client-authentication-method: POST
                        authorization-grant-type: authorization_code
                        scope:
                            - account_email
                        client-name: Kakao
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id

